[package]
name = "blueberry-generator-c"
version = "0.1.0"
edition = "2024"

[dependencies]
blueberry-ast = { path = "../../ast" }
blueberry-codegen-core = { path = "../codegen-core" }
quote = "1.0"
proc-macro2 = "1.0"
genco = "0.19"

[dev-dependencies]
blueberry-parser = { path = "../../parser" }
